### ISSUE TITLE
plotOntologyHeatmapCollapsed function got an error

### ISSUE THREAD

**Issue by Angel-Wei** [kharchenkolab/cacoa#45]
Hi, I ran into an error when I called `cao$plotOntologyHeatmapCollapsed` function. I got an error 
```r
Error in `chr_as_locations()`:
! Can't rename columns that don't exist.
✖ Column `qvalues` doesn't exist.
``` 

Before I come to this step, everything ran well and functions `cao$estimateDEPerCellType` and `cao$estimateOntology` (I used` 'GSEA'`)also worked. Here's some output info I got from `rlang::last_error()`:
```
> pdf(paste0(rep.name, '/', rep.name,"_plotOntologyHeatmapCollapsed_up_in_MUT.pdf"), height=15, width=10)
> print(cao$plotOntologyHeatmapCollapsed(
+   name="GSEA", genes="up", n=50, clust.method="ward.D", size.range=c(1, 4)) + ggtitle("Up in MUT"))
Error in (function (cond)  : 
  error in evaluating the argument 'x' in selecting a method for function 'print': Can't rename columns that don't exist.
✖ Column `qvalues` doesn't exist.
> rlang::last_error()
<error/vctrs_error_subscript_oob>
Error in `chr_as_locations()`:
! Can't rename columns that don't exist.
✖ Column `qvalues` doesn't exist.
---
Backtrace:
  1. cao$plotOntologyHeatmapCollapsed(...)
  6. dplyr:::rename.data.frame(., geneID = core_enrichment, qvalue = qvalues)
  7. tidyselect::eval_rename(expr(c(...)), .data)
  8. tidyselect:::rename_impl(...)
  9. tidyselect:::eval_select_impl(...)
 18. tidyselect:::vars_select_eval(...)
 19. tidyselect:::walk_data_tree(expr, data_mask, context_mask, error_call)
 20. tidyselect:::eval_c(expr, data_mask, context_mask)
 21. tidyselect:::reduce_sels(node, data_mask, context_mask, init = init)
 22. tidyselect:::walk_data_tree(new, data_mask, context_mask)
 23. tidyselect:::as_indices_sel_impl(...)
 24. tidyselect:::as_indices_impl(x, vars, call = call, strict = strict)
 25. tidyselect:::chr_as_locations(x, vars, call = call)
Run `rlang::last_trace()` to see the full context.
``` 
I wonder is there anything I can do to fix this problem to generate GSEA results? Thank you so much for the help in advance!

_Originally posted by @Angel-Wei in https://github.com/kharchenkolab/cacoa/issues/21#issuecomment-1499144887_

**Comment by rrydbirk** [comment]
Hi @Angel-Wei

Thanks for your interest in Cacoa. We're aware of this error, it should be fixed in the `dev` version. You can install this using `devtools::install_github("kharchenkolab/cacoa", ref="dev")`. If you saved your Cacoa object, you need to update it after installing, e.g., `cao %<>% Cacoa$new()`.

Could you let me know if this solves your problem?

BR

Rasmus

**Comment by Angel-Wei** [comment]
Hi Rasmus,

Sorry for the late reply. I actually tried to install the `dev` version. However, it gave me error and warning messages like this:
![Cacoa1](https://user-images.githubusercontent.com/39067474/234106638-5c67ee5e-589a-4e90-9808-ffcc35f53e55.png)
![Cacoa2](https://user-images.githubusercontent.com/39067474/234106640-7edf5d92-f7ae-4738-a576-fdfbd17a8cde.png)

**Comment by Angel-Wei** [comment]
Oh hi Rasmus! I think the` install.packages("sccore")` did not work in my case, which just installed the same version as I had. However, I found that the latest version can be installed via devtools:
<img width="845" alt="Screenshot 2023-04-27 at 2 45 21 PM" src="https://user-images.githubusercontent.com/39067474/234963261-54b744be-6b9b-4ec5-bf50-a9ce57823038.png">
Now my problem is solved and I can install the latest version of cacoa and plot the heatmap of GSEA. Thank you so much for the help!

**Comment by rrydbirk** [comment]
Hi @Angel-Wei 
Thanks for the feedback, glad it worked for you!

@evanbiederstedt, am I missing something here, why is `sccore` v. 1.0.3 not installing per default?

/Rasmus

**Comment by Angel-Wei** [comment]
Hi Rasmus,

Just an update of this function error. I realized that it worked after I re-install the latest Cacoa and use 
`cao %<>% Cacoa$new()` on a previously saved old Cacoa object.
However, if re-run Cacoa pipeline using the latest version, for the new `caoI` object, I still encountered errors like this:
<img width="861" alt="Screenshot 2023-06-20 at 2 48 59 PM" src="https://github.com/kharchenkolab/cacoa/assets/39067474/ad80e76b-aa5a-4e47-a718-d5e931f4e65e">

Also, I couldn't use function
`cao$estimateMetadataSeparation(sample.meta=cao$misc$sample_metadata)$padjust` #47 
I wonder is there any way around to address these problems? Thank you so much for the help!

Best,
Angel

**Comment by rrydbirk** [comment]
Hi @Angel-Wei 

This was fixed some time ago [here](https://github.com/kharchenkolab/cacoa/commit/91dfb6afea95925b2c3baa7370ec138bbb5bd97c#diff-05a3d32e8ad29b5b2ba305c50c8a1079d3134d8664ae09a671aeeb838f517c6cL3022).

Could you check `cao$.__enclos_env__$private$getOntologyPvalueResults` and see if it's correct there in the function definition? It should be
```
    if (type == "GSEA") {
        if ((nrow(ont.res) == 0) && !("core_enrichment" %in% 
            colnames(ont.res))) {
            ont.res$core_enrichment <- character()
        }
        ont.res %<>% rename(geneID = core_enrichment)
```

I just checked our copy constructor, private functions should be updated as well with `cao %<>% Cacoa$new()`.

**Comment by rrydbirk** [comment]
No worries, as long as it's working, all is good :-) Thanks for using our software!
